/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionBlockRead {
    /// a more descriptive name for the action
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// optional description string explaining what this action represents in your system
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    /// Unique id of the action
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// action key
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl ActionBlockRead {
    pub fn new(id: uuid::Uuid) -> ActionBlockRead {
        ActionBlockRead {
            name: None,
            description: None,
            attributes: None,
            id,
            key: None,
        }
    }
}

