/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddRolePermissions {
    /// List of permissions to assign to the role. If a permission is already granted to the role it is skipped. Each permission can be either a resource action id, or `{resource_key}:{action_key}`, i.e: the \"permission name\".
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl AddRolePermissions {
    pub fn new(permissions: Vec<String>) -> AddRolePermissions {
        AddRolePermissions {
            permissions,
        }
    }
}

