/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuditLogSortKey : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuditLogSortKey {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "timestamp")]
    Timestamp,

}

impl ToString for AuditLogSortKey {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::Timestamp => String::from("timestamp"),
        }
    }
}

impl Default for AuditLogSortKey {
    fn default() -> AuditLogSortKey {
        Self::None
    }
}

