/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogObjectsModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "organization_object", skip_serializing_if = "Option::is_none")]
    pub organization_object: Option<Box<models::OrganizationObject>>,
    #[serde(rename = "project_object", skip_serializing_if = "Option::is_none")]
    pub project_object: Option<Box<models::ProjectObject>>,
    #[serde(rename = "environment_object", skip_serializing_if = "Option::is_none")]
    pub environment_object: Option<Box<models::EnvironmentObject>>,
    #[serde(rename = "pdp_config_object", skip_serializing_if = "Option::is_none")]
    pub pdp_config_object: Option<Box<models::PdpConfigObject>>,
    #[serde(rename = "user_object", skip_serializing_if = "Option::is_none")]
    pub user_object: Option<Box<models::UserObj>>,
    #[serde(rename = "action_object", skip_serializing_if = "Option::is_none")]
    pub action_object: Option<Box<models::ActionObj>>,
    #[serde(rename = "resource_type_object", skip_serializing_if = "Option::is_none")]
    pub resource_type_object: Option<Box<models::ResourceTypeObj>>,
    #[serde(rename = "tenant_object", skip_serializing_if = "Option::is_none")]
    pub tenant_object: Option<Box<models::TenantObj>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl AuditLogObjectsModel {
    pub fn new() -> AuditLogObjectsModel {
        AuditLogObjectsModel {
            id: None,
            organization_object: None,
            project_object: None,
            environment_object: None,
            pdp_config_object: None,
            user_object: None,
            action_object: None,
            resource_type_object: None,
            tenant_object: None,
            created_at: None,
        }
    }
}

