/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// BillingTier : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingTier {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "enterprise")]
    Enterprise,

}

impl ToString for BillingTier {
    fn to_string(&self) -> String {
        match self {
            Self::Free => String::from("free"),
            Self::Pro => String::from("pro"),
            Self::Enterprise => String::from("enterprise"),
        }
    }
}

impl Default for BillingTier {
    fn default() -> BillingTier {
        Self::Free
    }
}

