/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkRoleUnAssignmentReport {
    #[serde(rename = "assignments_removed", skip_serializing_if = "Option::is_none")]
    pub assignments_removed: Option<i32>,
}

impl BulkRoleUnAssignmentReport {
    pub fn new() -> BulkRoleUnAssignmentReport {
        BulkRoleUnAssignmentReport {
            assignments_removed: None,
        }
    }
}

