/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ConditionSetType : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConditionSetType {
    #[serde(rename = "userset")]
    Userset,
    #[serde(rename = "resourceset")]
    Resourceset,

}

impl ToString for ConditionSetType {
    fn to_string(&self) -> String {
        match self {
            Self::Userset => String::from("userset"),
            Self::Resourceset => String::from("resourceset"),
        }
    }
}

impl Default for ConditionSetType {
    fn default() -> ConditionSetType {
        Self::Userset
    }
}

