/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionSetRead {
    /// A unique id by which Permit will identify the condition set. The key will be used as the generated rego rule name.
    #[serde(rename = "key")]
    pub key: String,
    /// the type of the set: UserSet or ResourceSet
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ConditionSetType>,
    /// whether the set was autogenerated by the system.
    #[serde(rename = "autogenerated", skip_serializing_if = "Option::is_none")]
    pub autogenerated: Option<bool>,
    #[serde(rename = "resource_id", skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<Box<models::ResourceId>>,
    /// Unique id of the condition set
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Unique id of the organization that the condition set belongs to.
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    /// Unique id of the project that the condition set belongs to.
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    /// Unique id of the environment that the condition set belongs to.
    #[serde(rename = "environment_id")]
    pub environment_id: uuid::Uuid,
    /// Date and time when the condition set was created (ISO_8601 format).
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Date and time when the condition set was last updated/modified (ISO_8601 format).
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<models::ResourceRead>>,
    /// A descriptive name for the set, i.e: 'US based employees' or 'Users behind VPN'
    #[serde(rename = "name")]
    pub name: String,
    /// an optional longer description of the set
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// a boolean expression that consists of multiple conditions, with and/or logic.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<serde_json::Value>,
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Box<models::ParentId>>,
}

impl ConditionSetRead {
    pub fn new(key: String, id: uuid::Uuid, organization_id: uuid::Uuid, project_id: uuid::Uuid, environment_id: uuid::Uuid, created_at: String, updated_at: String, name: String) -> ConditionSetRead {
        ConditionSetRead {
            key,
            r#type: None,
            autogenerated: None,
            resource_id: None,
            id,
            organization_id,
            project_id,
            environment_id,
            created_at,
            updated_at,
            resource: None,
            name,
            description: None,
            conditions: None,
            parent_id: None,
        }
    }
}

