/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionSetRuleRemove {
    /// The userset that will be unassigned these permission, i.e: all the users matching this rule will lose the specified permission
    #[serde(rename = "user_set")]
    pub user_set: String,
    /// The permission that will be removed from the userset *on* the resourceset. The permission can be either a resource action id, or `{resource_key}:{action_key}`, i.e: the \"permission name\".
    #[serde(rename = "permission")]
    pub permission: String,
    /// The resourceset that represents the resources that are no longer granted for access, i.e: all the resources matching this rule can no longer be accessed by the userset, and will be revoked the specified *permission*
    #[serde(rename = "resource_set")]
    pub resource_set: String,
    /// if True, will set the condition set rule to the role's autogen user-set.
    #[serde(rename = "is_role", skip_serializing_if = "Option::is_none")]
    pub is_role: Option<bool>,
    /// if True, will set the condition set rule to the resource's autogen resource-set.
    #[serde(rename = "is_resource", skip_serializing_if = "Option::is_none")]
    pub is_resource: Option<bool>,
}

impl ConditionSetRuleRemove {
    pub fn new(user_set: String, permission: String, resource_set: String) -> ConditionSetRuleRemove {
        ConditionSetRuleRemove {
            user_set,
            permission,
            resource_set,
            is_role: None,
            is_resource: None,
        }
    }
}

