/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Data : Data payload to embed within the data update (instead of having the client fetch it from the url).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Data {
}

impl Data {
    /// Data payload to embed within the data update (instead of having the client fetch it from the url).
    pub fn new() -> Data {
        Data {
        }
    }
}

