/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// DataSourceConfig : Static list of Data Source Entries returned to client.  Answers this question for the client: from where should i get the full picture of data i need? (as opposed to incremental data updates)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataSourceConfig {
    /// list of data sources and how to fetch from them
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::DataSourceEntryWithPollingInterval>>,
}

impl DataSourceConfig {
    /// Static list of Data Source Entries returned to client.  Answers this question for the client: from where should i get the full picture of data i need? (as opposed to incremental data updates)
    pub fn new() -> DataSourceConfig {
        DataSourceConfig {
            entries: None,
        }
    }
}

