/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalUsage {
    #[serde(rename = "current_month", skip_serializing_if = "Option::is_none")]
    pub current_month: Option<Box<models::MonthlyUsage>>,
    #[serde(rename = "previous_month", skip_serializing_if = "Option::is_none")]
    pub previous_month: Option<Box<models::MonthlyUsage>>,
    #[serde(rename = "two_months_ago", skip_serializing_if = "Option::is_none")]
    pub two_months_ago: Option<Box<models::MonthlyUsage>>,
}

impl HistoricalUsage {
    pub fn new() -> HistoricalUsage {
        HistoricalUsage {
            current_month: None,
            previous_month: None,
            two_months_ago: None,
        }
    }
}

