/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwksObj {
    /// The keys to match against the request headers
    #[serde(rename = "keys")]
    pub keys: Vec<serde_json::Value>,
}

impl JwksObj {
    pub fn new(keys: Vec<serde_json::Value>) -> JwksObj {
        JwksObj {
            keys,
        }
    }
}

