/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// MemberAccessLevel : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MemberAccessLevel {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "no_access")]
    NoAccess,

}

impl ToString for MemberAccessLevel {
    fn to_string(&self) -> String {
        match self {
            Self::Admin => String::from("admin"),
            Self::Write => String::from("write"),
            Self::Read => String::from("read"),
            Self::NoAccess => String::from("no_access"),
        }
    }
}

impl Default for MemberAccessLevel {
    fn default() -> MemberAccessLevel {
        Self::Admin
    }
}

