/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpaLabels {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
}

impl OpaLabels {
    pub fn new(id: uuid::Uuid, version: String) -> OpaLabels {
        OpaLabels {
            id,
            version,
        }
    }
}

