/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgMemberUpdate {
    /// Custom permit.io dashboard settings, such as preferred theme, etc.
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    /// updates the onboarding step (optional)
    #[serde(rename = "onboarding_step", skip_serializing_if = "Option::is_none")]
    pub onboarding_step: Option<models::OnboardingStep>,
}

impl OrgMemberUpdate {
    pub fn new() -> OrgMemberUpdate {
        OrgMemberUpdate {
            settings: None,
            onboarding_step: None,
        }
    }
}

