/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationCreate {
    /// A URL-friendly name of the organization (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the organization.
    #[serde(rename = "key")]
    pub key: String,
    /// The name of the organization, usually it's your company's name.
    #[serde(rename = "name")]
    pub name: String,
    /// the settings for this project
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

impl OrganizationCreate {
    pub fn new(key: String, name: String) -> OrganizationCreate {
        OrganizationCreate {
            key,
            name,
            settings: None,
        }
    }
}

