/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationStatistics {
    #[serde(rename = "projects")]
    pub projects: i32,
    #[serde(rename = "environments")]
    pub environments: i32,
    #[serde(rename = "users")]
    pub users: i32,
}

impl OrganizationStatistics {
    pub fn new(projects: i32, environments: i32, users: i32) -> OrganizationStatistics {
        OrganizationStatistics {
            projects,
            environments,
            users,
        }
    }
}

