/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdpConfigVersion {
    /// The minimum image version of PDP that can connect to this config
    #[serde(rename = "min_pdp_version", skip_serializing_if = "Option::is_none")]
    pub min_pdp_version: Option<String>,
}

impl PdpConfigVersion {
    pub fn new() -> PdpConfigVersion {
        PdpConfigVersion {
            min_pdp_version: None,
        }
    }
}

