/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdpConfigObj {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
}

impl PdpConfigObj {
    pub fn new(id: uuid::Uuid, name: String) -> PdpConfigObj {
        PdpConfigObj {
            id,
            name,
        }
    }
}

