/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectRead {
    /// A URL-friendly name of the project (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the project.
    #[serde(rename = "key")]
    pub key: String,
    /// Optional namespace for URNs. If empty, URNs will be generated from project key.
    #[serde(rename = "urn_namespace", skip_serializing_if = "Option::is_none")]
    pub urn_namespace: Option<String>,
    /// Unique id of the project
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Unique id of the organization that the project belongs to.
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    /// Date and time when the project was created (ISO_8601 format).
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Date and time when the project was last updated/modified (ISO_8601 format).
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// The name of the project
    #[serde(rename = "name")]
    pub name: String,
    /// a longer description outlining the project objectives
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// the settings for this project
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    /// the id of the policy repo to use for this project
    #[serde(rename = "active_policy_repo_id", skip_serializing_if = "Option::is_none")]
    pub active_policy_repo_id: Option<uuid::Uuid>,
}

impl ProjectRead {
    pub fn new(key: String, id: uuid::Uuid, organization_id: uuid::Uuid, created_at: String, updated_at: String, name: String) -> ProjectRead {
        ProjectRead {
            key,
            urn_namespace: None,
            id,
            organization_id,
            created_at,
            updated_at,
            name,
            description: None,
            settings: None,
            active_policy_repo_id: None,
        }
    }
}

