/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProxyConfigCreate {
    #[serde(rename = "secret")]
    pub secret: Box<models::Secret>,
    /// Proxy Config is set to enable the Permit Proxy to make proxied requests as part of the Frontend AuthZ.
    #[serde(rename = "key")]
    pub key: String,
    /// The name of the proxy config, for example: 'Stripe API'
    #[serde(rename = "name")]
    pub name: String,
    /// Proxy config mapping rules will include the rules that will be used to map the request to the backend service by a URL and a http method.
    #[serde(rename = "mapping_rules", skip_serializing_if = "Option::is_none")]
    pub mapping_rules: Option<Vec<models::MappingRule>>,
    /// Proxy config auth mechanism will define the authentication mechanism that will be used to authenticate the request.  Bearer injects the secret into the Authorization header as a Bearer token,  Basic injects the secret into the Authorization header as a Basic user:password,  Headers injects plain headers into the request.
    #[serde(rename = "auth_mechanism", skip_serializing_if = "Option::is_none")]
    pub auth_mechanism: Option<models::AuthMechanism>,
}

impl ProxyConfigCreate {
    pub fn new(secret: models::Secret, key: String, name: String) -> ProxyConfigCreate {
        ProxyConfigCreate {
            secret: Box::new(secret),
            key,
            name,
            mapping_rules: None,
            auth_mechanism: None,
        }
    }
}

