/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelationshipTupleDeleteBulkOperation {
    #[serde(rename = "idents")]
    pub idents: Vec<models::RelationshipTupleDelete>,
}

impl RelationshipTupleDeleteBulkOperation {
    pub fn new(idents: Vec<models::RelationshipTupleDelete>) -> RelationshipTupleDeleteBulkOperation {
        RelationshipTupleDeleteBulkOperation {
            idents,
        }
    }
}

