/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelationRead {
    /// An optional longer description of what this relation represents in your system
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The subject resource ID or key
    #[serde(rename = "subject_resource")]
    pub subject_resource: String,
    /// A URL-friendly name of the relation (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the relation.
    #[serde(rename = "key")]
    pub key: String,
    /// The name of the relation
    #[serde(rename = "name")]
    pub name: String,
    /// Unique id of the relation
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Unique id of the organization that the relation belongs to.
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    /// Unique id of the project that the relation belongs to.
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    /// Unique id of the environment that the relation belongs to.
    #[serde(rename = "environment_id")]
    pub environment_id: uuid::Uuid,
    /// Date and time when the relation was created (ISO_8601 format).
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Date and time when the relation was last updated/modified (ISO_8601 format).
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// The object resource id
    #[serde(rename = "object_resource_id")]
    pub object_resource_id: uuid::Uuid,
    /// The object resource key
    #[serde(rename = "object_resource")]
    pub object_resource: String,
    /// The subject resource id
    #[serde(rename = "subject_resource_id")]
    pub subject_resource_id: uuid::Uuid,
}

impl RelationRead {
    pub fn new(subject_resource: String, key: String, name: String, id: uuid::Uuid, organization_id: uuid::Uuid, project_id: uuid::Uuid, environment_id: uuid::Uuid, created_at: String, updated_at: String, object_resource_id: uuid::Uuid, object_resource: String, subject_resource_id: uuid::Uuid) -> RelationRead {
        RelationRead {
            description: None,
            subject_resource,
            key,
            name,
            id,
            organization_id,
            project_id,
            environment_id,
            created_at,
            updated_at,
            object_resource_id,
            object_resource,
            subject_resource_id,
        }
    }
}

