/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// RequestStatus : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "canceled")]
    Canceled,

}

impl ToString for RequestStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Pending => String::from("pending"),
            Self::Approved => String::from("approved"),
            Self::Denied => String::from("denied"),
            Self::Canceled => String::from("canceled"),
        }
    }
}

impl Default for RequestStatus {
    fn default() -> RequestStatus {
        Self::Pending
    }
}

