/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceActionGroupRead {
    /// The name of the action group
    #[serde(rename = "name")]
    pub name: String,
    /// An optional longer description of what this action group represents in your system
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// optional dictionary of key-value pairs that can be used to store arbitrary metadata about this action group. This metadata can be used to filter action groups using query parameters with attr_ prefix
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<String>>,
    /// A URL-friendly name of the action group (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the action group.
    #[serde(rename = "key")]
    pub key: String,
    /// Unique id of the action group
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Unique id of the organization that the action group belongs to.
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    /// Unique id of the project that the action group belongs to.
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    /// Unique id of the environment that the action group belongs to.
    #[serde(rename = "environment_id")]
    pub environment_id: uuid::Uuid,
    /// Unique id of the resource that the action group belongs to.
    #[serde(rename = "resource_id")]
    pub resource_id: uuid::Uuid,
    /// Date and time when the action group was created (ISO_8601 format).
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Date and time when the action group was last updated/modified (ISO_8601 format).
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ResourceActionGroupRead {
    pub fn new(name: String, key: String, id: uuid::Uuid, organization_id: uuid::Uuid, project_id: uuid::Uuid, environment_id: uuid::Uuid, resource_id: uuid::Uuid, created_at: String, updated_at: String) -> ResourceActionGroupRead {
        ResourceActionGroupRead {
            name,
            description: None,
            attributes: None,
            actions: None,
            key,
            id,
            organization_id,
            project_id,
            environment_id,
            resource_id,
            created_at,
            updated_at,
        }
    }
}

