/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ResourceId : For ResourceSets, the id of the base resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceId {
}

impl ResourceId {
    /// For ResourceSets, the id of the base resource.
    pub fn new() -> ResourceId {
        ResourceId {
        }
    }
}

