/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceInstanceUpdate {
    /// Arbitrary resource attributes that will be used to enforce attribute-based access control policies.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
}

impl ResourceInstanceUpdate {
    pub fn new() -> ResourceInstanceUpdate {
        ResourceInstanceUpdate {
            attributes: None,
        }
    }
}

