/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
    id: String,
    user: String,
    role: String,
    tenant: Option<String>,
    resource_instance: Option<String>,
    resource_instance_id: Option<String>,
    user_id: String,
    role_id: String,
    tenant_id: String,
    organization_id: String,
    project_id: String,
    environment_id: String,
    created_at: String,
}

impl ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
    pub fn new() -> ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
        ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
        }
    }
}

