/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
}

impl ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
    pub fn new() -> ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
        ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet {
        }
    }
}

