/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignmentDetailedRead {
    /// Unique id of the role assignment
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// the role that is assigned
    #[serde(rename = "role")]
    pub role: Box<models::RoleAssignmentRole>,
    /// the user the role is assigned to
    #[serde(rename = "user")]
    pub user: Box<models::RoleAssignmentUser>,
    /// the tenant the role is associated with
    #[serde(rename = "tenant")]
    pub tenant: Box<models::RoleAssignmentTenant>,
    #[serde(rename = "resource_instance", skip_serializing_if = "Option::is_none")]
    pub resource_instance: Option<Box<models::RoleAssignmentResourceInstance>>,
    /// Unique id of the organization that the role assignment belongs to.
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    /// Unique id of the project that the role assignment belongs to.
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    /// Unique id of the environment that the role assignment belongs to.
    #[serde(rename = "environment_id")]
    pub environment_id: uuid::Uuid,
    /// Date and time when the role assignment was created (ISO_8601 format).
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl RoleAssignmentDetailedRead {
    pub fn new(id: uuid::Uuid, role: models::RoleAssignmentRole, user: models::RoleAssignmentUser, tenant: models::RoleAssignmentTenant, organization_id: uuid::Uuid, project_id: uuid::Uuid, environment_id: uuid::Uuid, created_at: String) -> RoleAssignmentDetailedRead {
        RoleAssignmentDetailedRead {
            id,
            role: Box::new(role),
            user: Box::new(user),
            tenant: Box::new(tenant),
            resource_instance: None,
            organization_id,
            project_id,
            environment_id,
            created_at,
        }
    }
}

