/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignmentResourceInstance {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
}

impl RoleAssignmentResourceInstance {
    pub fn new(id: uuid::Uuid, key: String, resource: String) -> RoleAssignmentResourceInstance {
        RoleAssignmentResourceInstance {
            id,
            key,
            resource,
            attributes: None,
        }
    }
}

