/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// SearchOperator : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchOperator {
    #[serde(rename = "startswith")]
    Startswith,
    #[serde(rename = "endswith")]
    Endswith,
    #[serde(rename = "contains")]
    Contains,

}

impl ToString for SearchOperator {
    fn to_string(&self) -> String {
        match self {
            Self::Startswith => String::from("startswith"),
            Self::Endswith => String::from("endswith"),
            Self::Contains => String::from("contains"),
        }
    }
}

impl Default for SearchOperator {
    fn default() -> SearchOperator {
        Self::Startswith
    }
}

