/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantCreateBulkOperation {
    #[serde(rename = "operations")]
    pub operations: Vec<models::TenantCreate>,
}

impl TenantCreateBulkOperation {
    pub fn new(operations: Vec<models::TenantCreate>) -> TenantCreateBulkOperation {
        TenantCreateBulkOperation {
            operations,
        }
    }
}

