/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRole {
    /// the role that is assigned
    #[serde(rename = "role")]
    pub role: String,
    /// the tenant the role is associated with
    #[serde(rename = "tenant")]
    pub tenant: String,
}

impl UserRole {
    pub fn new(role: String, tenant: String) -> UserRole {
        UserRole {
            role,
            tenant,
        }
    }
}

