/*
 * Permit.io API
 *
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserReplaceBulkOperation {
    #[serde(rename = "operations")]
    pub operations: Vec<models::UserCreate>,
}

impl UserReplaceBulkOperation {
    pub fn new(operations: Vec<models::UserCreate>) -> UserReplaceBulkOperation {
        UserReplaceBulkOperation {
            operations,
        }
    }
}

